package br.com.savetheday.entities;

public enum Categoria {
    INCLUCAO_DE_PESSOAS_COM_DEFICIENCIA_,ASSISTENCIA_SOCIAL, CULTURA, SAUDE, MEIO_AMBIENTE, DESENVOLVIMENTO_E_DEFESA_DOS_DIREITOS, HABITACAO, DIREITOS_DOS_ANIMAIS, EDUCACAO_E_PESQUISA;


}