server:
  port: 8080
spring:
  profiles:
    active: teste

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/savetheday
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      jdbc:
        lob:
          non_contextual_creation: true


---


spring:
  profiles: teste
  datasource:
    url: jdbc:mysql://localhost:3306/salveodia?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      jdbc:
        lob:
          non_contextual_creation: true


